{{- if and .Values.rbac.create .Values.rbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dozzle.fullname" . }}
  labels:
    {{- include "dozzle.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dozzle.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "dozzle.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}