apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dozzle
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
