name: Bug Report
labels: ["bug"]
description: |
  Use this template if something is not working as expected.
body:
  - type: markdown
    attributes:
      value: |
        I get an overwhelming of issues which take coniserable amount of time to investigate. Most often, they are configuration related.
        For this reason, I ask you to help me by providing as much information as possible.
        For issues with `docker-socket-proxy` I may not be able to help as those are not related to Dozzle.
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
      options:
        - label: Completed
          required: true
  - type: dropdown
    attributes:
      label: How is Dozzle deployed?
      description: Select the components that you are using.
      options:
        - Standalone Deployment
        - Agents
        - Remote Hosts
        - Swarm Mode
    validations:
      required: true
  - type: input
    attributes:
      label: Dozzle version
      description: Can be found in logs or settings page.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug / provide steps to reproduce it
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Run `docker system info` and paste the output in the field below..
    validations:
      required: true
  - type: textarea
    attributes:
      label: If applicable, add screenshots to help explain your vision of the feature
      description: Drag issues into the text input below
    validations:
      required: false
  - type: textarea
    attributes:
      label: If applicable, attach your Dozzle logs. You many need to enable [debug mode](https://dozzle.dev/guide/debugging) to see more logs.
    validations:
      required: false
