// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerAction int32

const (
	ContainerAction_Start   ContainerAction = 0
	ContainerAction_Stop    ContainerAction = 1
	ContainerAction_Restart ContainerAction = 2
)

// Enum value maps for ContainerAction.
var (
	ContainerAction_name = map[int32]string{
		0: "Start",
		1: "Stop",
		2: "Restart",
	}
	ContainerAction_value = map[string]int32{
		"Start":   0,
		"Stop":    1,
		"Restart": 2,
	}
)

func (x ContainerAction) Enum() *ContainerAction {
	p := new(ContainerAction)
	*p = x
	return p
}

func (x ContainerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ContainerAction) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ContainerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerAction.Descriptor instead.
func (ContainerAction) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // deprecated
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	ImageId       string                 `protobuf:"bytes,6,opt,name=ImageId,proto3" json:"ImageId,omitempty"` // deprecated
	Created       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Started       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started,proto3" json:"started,omitempty"`
	Health        string                 `protobuf:"bytes,9,opt,name=health,proto3" json:"health,omitempty"`
	Host          string                 `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	Tty           bool                   `protobuf:"varint,11,opt,name=tty,proto3" json:"tty,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stats         []*ContainerStat       `protobuf:"bytes,13,rep,name=stats,proto3" json:"stats,omitempty"`
	Group         string                 `protobuf:"bytes,14,opt,name=group,proto3" json:"group,omitempty"`
	Command       string                 `protobuf:"bytes,15,opt,name=command,proto3" json:"command,omitempty"`
	Finished      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=finished,proto3" json:"finished,omitempty"`
	MemoryLimit   uint64                 `protobuf:"varint,17,opt,name=memoryLimit,proto3" json:"memoryLimit,omitempty"`
	CpuLimit      float64                `protobuf:"fixed64,18,opt,name=cpuLimit,proto3" json:"cpuLimit,omitempty"`
	FullyLoaded   bool                   `protobuf:"varint,19,opt,name=fullyLoaded,proto3" json:"fullyLoaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Container) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Container) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *Container) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Container) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Container) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *Container) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Container) GetStats() []*ContainerStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Container) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Container) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Container) GetFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.Finished
	}
	return nil
}

func (x *Container) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Container) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *Container) GetFullyLoaded() bool {
	if x != nil {
		return x.FullyLoaded
	}
	return false
}

type ContainerStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memoryPercent,proto3" json:"memoryPercent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStat) Reset() {
	*x = ContainerStat{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStat) ProtoMessage() {}

func (x *ContainerStat) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStat.ProtoReflect.Descriptor instead.
func (*ContainerStat) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerStat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerStat) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ContainerStat) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Message       *anypb.Any             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Stream        string                 `protobuf:"bytes,6,opt,name=stream,proto3" json:"stream,omitempty"`
	Position      string                 `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	RawMessage    string                 `protobuf:"bytes,8,opt,name=rawMessage,proto3" json:"rawMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *LogEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogEvent) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LogEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEvent) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *LogEvent) GetRawMessage() string {
	if x != nil {
		return x.RawMessage
	}
	return ""
}

type SimpleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ComplexMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexMessage) Reset() {
	*x = ComplexMessage{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMessage) ProtoMessage() {}

func (x *ComplexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMessage.ProtoReflect.Descriptor instead.
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *ComplexMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContainerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ContainerEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ContainerEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Host struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeAddress     string                 `protobuf:"bytes,3,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	Swarm           bool                   `protobuf:"varint,4,opt,name=swarm,proto3" json:"swarm,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperatingSystem string                 `protobuf:"bytes,6,opt,name=operatingSystem,proto3" json:"operatingSystem,omitempty"`
	OsVersion       string                 `protobuf:"bytes,7,opt,name=osVersion,proto3" json:"osVersion,omitempty"`
	OsType          string                 `protobuf:"bytes,8,opt,name=osType,proto3" json:"osType,omitempty"`
	CpuCores        uint32                 `protobuf:"varint,9,opt,name=cpuCores,proto3" json:"cpuCores,omitempty"`
	Memory          uint64                 `protobuf:"varint,10,opt,name=memory,proto3" json:"memory,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,11,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	DockerVersion   string                 `protobuf:"bytes,12,opt,name=dockerVersion,proto3" json:"dockerVersion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Host) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *Host) GetSwarm() bool {
	if x != nil {
		return x.Swarm
	}
	return false
}

func (x *Host) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Host) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Host) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Host) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *Host) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Host) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Host) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Host) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xa2\x05\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\aImageId\x18\x06 \x01(\tR\aImageId\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\astarted\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12\x16\n" +
	"\x06health\x18\t \x01(\tR\x06health\x12\x12\n" +
	"\x04host\x18\n" +
	" \x01(\tR\x04host\x12\x10\n" +
	"\x03tty\x18\v \x01(\bR\x03tty\x127\n" +
	"\x06labels\x18\f \x03(\v2\x1f.protobuf.Container.LabelsEntryR\x06labels\x12-\n" +
	"\x05stats\x18\r \x03(\v2\x17.protobuf.ContainerStatR\x05stats\x12\x14\n" +
	"\x05group\x18\x0e \x01(\tR\x05group\x12\x18\n" +
	"\acommand\x18\x0f \x01(\tR\acommand\x126\n" +
	"\bfinished\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bfinished\x12 \n" +
	"\vmemoryLimit\x18\x11 \x01(\x04R\vmemoryLimit\x12\x1a\n" +
	"\bcpuLimit\x18\x12 \x01(\x01R\bcpuLimit\x12 \n" +
	"\vfullyLoaded\x18\x13 \x01(\bR\vfullyLoaded\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\rContainerStat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"cpuPercent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\vmemoryUsage\x18\x03 \x01(\x01R\vmemoryUsage\x12$\n" +
	"\rmemoryPercent\x18\x04 \x01(\x01R\rmemoryPercent\"\x90\x02\n" +
	"\bLogEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vcontainerId\x18\x02 \x01(\tR\vcontainerId\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\tR\x06stream\x12\x1a\n" +
	"\bposition\x18\a \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"rawMessage\x18\b \x01(\tR\n" +
	"rawMessage\")\n" +
	"\rSimpleMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x0eComplexMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8c\x01\n" +
	"\x0eContainerEvent\x12\x18\n" +
	"\aactorId\x18\x01 \x01(\tR\aactorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xaf\x03\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vnodeAddress\x18\x03 \x01(\tR\vnodeAddress\x12\x14\n" +
	"\x05swarm\x18\x04 \x01(\bR\x05swarm\x122\n" +
	"\x06labels\x18\x05 \x03(\v2\x1a.protobuf.Host.LabelsEntryR\x06labels\x12(\n" +
	"\x0foperatingSystem\x18\x06 \x01(\tR\x0foperatingSystem\x12\x1c\n" +
	"\tosVersion\x18\a \x01(\tR\tosVersion\x12\x16\n" +
	"\x06osType\x18\b \x01(\tR\x06osType\x12\x1a\n" +
	"\bcpuCores\x18\t \x01(\rR\bcpuCores\x12\x16\n" +
	"\x06memory\x18\n" +
	" \x01(\x04R\x06memory\x12\"\n" +
	"\fagentVersion\x18\v \x01(\tR\fagentVersion\x12$\n" +
	"\rdockerVersion\x18\f \x01(\tR\rdockerVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*3\n" +
	"\x0fContainerAction\x12\t\n" +
	"\x05Start\x10\x00\x12\b\n" +
	"\x04Stop\x10\x01\x12\v\n" +
	"\aRestart\x10\x02B\x13Z\x11internal/agent/pbb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_types_proto_goTypes = []any{
	(ContainerAction)(0),          // 0: protobuf.ContainerAction
	(*Container)(nil),             // 1: protobuf.Container
	(*ContainerStat)(nil),         // 2: protobuf.ContainerStat
	(*LogEvent)(nil),              // 3: protobuf.LogEvent
	(*SimpleMessage)(nil),         // 4: protobuf.SimpleMessage
	(*ComplexMessage)(nil),        // 5: protobuf.ComplexMessage
	(*ContainerEvent)(nil),        // 6: protobuf.ContainerEvent
	(*Host)(nil),                  // 7: protobuf.Host
	nil,                           // 8: protobuf.Container.LabelsEntry
	nil,                           // 9: protobuf.Host.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 11: google.protobuf.Any
}
var file_types_proto_depIdxs = []int32{
	10, // 0: protobuf.Container.created:type_name -> google.protobuf.Timestamp
	10, // 1: protobuf.Container.started:type_name -> google.protobuf.Timestamp
	8,  // 2: protobuf.Container.labels:type_name -> protobuf.Container.LabelsEntry
	2,  // 3: protobuf.Container.stats:type_name -> protobuf.ContainerStat
	10, // 4: protobuf.Container.finished:type_name -> google.protobuf.Timestamp
	11, // 5: protobuf.LogEvent.message:type_name -> google.protobuf.Any
	10, // 6: protobuf.LogEvent.timestamp:type_name -> google.protobuf.Timestamp
	10, // 7: protobuf.ContainerEvent.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 8: protobuf.Host.labels:type_name -> protobuf.Host.LabelsEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
