// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/amir20/dozzle/internal/container"
)

type Dispatcher struct {
	ID   int32   `json:"id"`
	Name string  `json:"name"`
	Type string  `json:"type"`
	URL  *string `json:"url,omitempty"`
}

type DispatcherInput struct {
	Name string  `json:"name"`
	Type string  `json:"type"`
	URL  *string `json:"url,omitempty"`
}

type Mutation struct {
}

type NotificationRule struct {
	ID                  int32       `json:"id"`
	Name                string      `json:"name"`
	Enabled             bool        `json:"enabled"`
	Dispatcher          *Dispatcher `json:"dispatcher"`
	LogExpression       string      `json:"logExpression"`
	ContainerExpression string      `json:"containerExpression"`
	TriggerCount        int         `json:"triggerCount"`
	LastTriggeredAt     *time.Time  `json:"lastTriggeredAt,omitempty"`
	TriggeredContainers int32       `json:"triggeredContainers"`
}

type NotificationRuleInput struct {
	Name                string `json:"name"`
	Enabled             bool   `json:"enabled"`
	DispatcherID        int32  `json:"dispatcherId"`
	LogExpression       string `json:"logExpression"`
	ContainerExpression string `json:"containerExpression"`
}

type NotificationRuleUpdateInput struct {
	Name                *string `json:"name,omitempty"`
	Enabled             *bool   `json:"enabled,omitempty"`
	DispatcherID        *int32  `json:"dispatcherId,omitempty"`
	LogExpression       *string `json:"logExpression,omitempty"`
	ContainerExpression *string `json:"containerExpression,omitempty"`
}

type PreviewInput struct {
	ContainerExpression string  `json:"containerExpression"`
	LogExpression       *string `json:"logExpression,omitempty"`
}

type PreviewResult struct {
	ContainerError    *string                `json:"containerError,omitempty"`
	LogError          *string                `json:"logError,omitempty"`
	MatchedContainers []*container.Container `json:"matchedContainers"`
	MatchedLogs       []*container.LogEvent  `json:"matchedLogs"`
	TotalLogs         int32                  `json:"totalLogs"`
}

type Query struct {
}
