services:
  dozzle-service:
    image: amir20/dozzle:local-test
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_MODE=swarm
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - dozzle
    deploy:
      mode: global

networks:
  dozzle:
    driver: overlay
