// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonCaretDown: typeof import('~icons/carbon/caret-down')['default']
    CilColumns: typeof import('~icons/cil/columns')['default']
    CilFindInPage: typeof import('~icons/cil/find-in-page')['default']
    ContainerStat: typeof import('./components/ContainerStat.vue')['default']
    ContainerTitle: typeof import('./components/ContainerTitle.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    FuzzySearchModal: typeof import('./components/FuzzySearchModal.vue')['default']
    InfiniteLoader: typeof import('./components/InfiniteLoader.vue')['default']
    LogActionsToolbar: typeof import('./components/LogActionsToolbar.vue')['default']
    LogContainer: typeof import('./components/LogContainer.vue')['default']
    LogEventSource: typeof import('./components/LogEventSource.vue')['default']
    LogViewer: typeof import('./components/LogViewer.vue')['default']
    LogViewerWithSource: typeof import('./components/LogViewerWithSource.vue')['default']
    MdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    MdiLightChevronDoubleDown: typeof import('~icons/mdi-light/chevron-double-down')['default']
    MdiLightChevronLeft: typeof import('~icons/mdi-light/chevron-left')['default']
    MdiLightChevronRight: typeof import('~icons/mdi-light/chevron-right')['default']
    MdiLightCog: typeof import('~icons/mdi-light/cog')['default']
    MdiLightMagnify: typeof import('~icons/mdi-light/magnify')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    OcticonContainer24: typeof import('~icons/octicon/container24')['default']
    OcticonDownload24: typeof import('~icons/octicon/download24')['default']
    OcticonTrash24: typeof import('~icons/octicon/trash24')['default']
    PastTime: typeof import('./components/PastTime.vue')['default']
    RelativeTime: typeof import('./components/RelativeTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableView: typeof import('./components/ScrollableView.vue')['default']
    ScrollProgress: typeof import('./components/ScrollProgress.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
}

export {}
