// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ContainerStat: typeof import('./components/ContainerStat.vue')['default']
    ContainerTitle: typeof import('./components/ContainerTitle.vue')['default']
    FuzzySearchModal: typeof import('./components/FuzzySearchModal.vue')['default']
    InfiniteLoader: typeof import('./components/InfiniteLoader.vue')['default']
    LogActionsToolbar: typeof import('./components/LogActionsToolbar.vue')['default']
    LogContainer: typeof import('./components/LogContainer.vue')['default']
    LogEventSource: typeof import('./components/LogEventSource.vue')['default']
    LogViewer: typeof import('./components/LogViewer.vue')['default']
    LogViewerWithSource: typeof import('./components/LogViewerWithSource.vue')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    PastTime: typeof import('./components/PastTime.vue')['default']
    RelativeTime: typeof import('./components/RelativeTime.vue')['default']
    ScrollableView: typeof import('./components/ScrollableView.vue')['default']
    ScrollProgress: typeof import('./components/ScrollProgress.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
}

export { }
