/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Carbon:caretDown': typeof import('~icons/carbon/caret-down')['default']
    'Cil:checkCircle': typeof import('~icons/cil/check-circle')['default']
    'Cil:columns': typeof import('~icons/cil/columns')['default']
    'Cil:findInPage': typeof import('~icons/cil/find-in-page')['default']
    ComplexLogItem: typeof import('./components/LogViewer/ComplexLogItem.vue')['default']
    ContainerStat: typeof import('./components/LogViewer/ContainerStat.vue')['default']
    ContainerTitle: typeof import('./components/LogViewer/ContainerTitle.vue')['default']
    DockerEventLogItem: typeof import('./components/LogViewer/DockerEventLogItem.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    FieldList: typeof import('./components/LogViewer/FieldList.vue')['default']
    FuzzySearchModal: typeof import('./components/FuzzySearchModal.vue')['default']
    InfiniteLoader: typeof import('./components/InfiniteLoader.vue')['default']
    LogActionsToolbar: typeof import('./components/LogViewer/LogActionsToolbar.vue')['default']
    LogContainer: typeof import('./components/LogViewer/LogContainer.vue')['default']
    LogDate: typeof import('./components/LogViewer/LogDate.vue')['default']
    LogEventSource: typeof import('./components/LogViewer/LogEventSource.vue')['default']
    LogLevel: typeof import('./components/LogViewer/LogLevel.vue')['default']
    LogViewer: typeof import('./components/LogViewer/LogViewer.vue')['default']
    LogViewerWithSource: typeof import('./components/LogViewer/LogViewerWithSource.vue')['default']
    'Mdi:dotsVertical': typeof import('~icons/mdi/dots-vertical')['default']
    'Mdi:lightChevronDoubleDown': typeof import('~icons/mdi-light/chevron-double-down')['default']
    'Mdi:lightChevronLeft': typeof import('~icons/mdi-light/chevron-left')['default']
    'Mdi:lightChevronRight': typeof import('~icons/mdi-light/chevron-right')['default']
    'Mdi:lightCog': typeof import('~icons/mdi-light/cog')['default']
    'Mdi:lightLogout': typeof import('~icons/mdi-light/logout')['default']
    'Mdi:lightMagnify': typeof import('~icons/mdi-light/magnify')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    'Octicon:container24': typeof import('~icons/octicon/container24')['default']
    'Octicon:download24': typeof import('~icons/octicon/download24')['default']
    'Octicon:trash24': typeof import('~icons/octicon/trash24')['default']
    PastTime: typeof import('./components/PastTime.vue')['default']
    RelativeTime: typeof import('./components/RelativeTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableView: typeof import('./components/ScrollableView.vue')['default']
    ScrollProgress: typeof import('./components/ScrollProgress.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    SimpleLogItem: typeof import('./components/LogViewer/SimpleLogItem.vue')['default']
    SkippedEntriesLogItem: typeof import('./components/LogViewer/SkippedEntriesLogItem.vue')['default']
    StatMonitor: typeof import('./components/LogViewer/StatMonitor.vue')['default']
    StatSparkline: typeof import('./components/LogViewer/StatSparkline.vue')['default']
    ZigZag: typeof import('./components/LogViewer/ZigZag.vue')['default']
  }
}
