/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/cloud/search': RouteRecordInfo<
      '/cloud/search',
      '/cloud/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/container/[id]': RouteRecordInfo<
      '/container/[id]',
      '/container/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/container/[id].time.[datetime]': RouteRecordInfo<
      '/container/[id].time.[datetime]',
      '/container/:id/time/:datetime',
      { datetime: ParamValue<true>, id: ParamValue<true> },
      { datetime: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/group/[name]': RouteRecordInfo<
      '/group/[name]',
      '/group/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/host/[id]': RouteRecordInfo<
      '/host/[id]',
      '/host/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/host-group/[name]': RouteRecordInfo<
      '/host-group/[name]',
      '/host-group/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mcp/authorize': RouteRecordInfo<
      '/mcp/authorize',
      '/mcp/authorize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/merged/[ids]': RouteRecordInfo<
      '/merged/[ids]',
      '/merged/:ids',
      { ids: ParamValue<true> },
      { ids: ParamValue<false> },
      | never
    >,
    '/namespace/[name]': RouteRecordInfo<
      '/namespace/[name]',
      '/namespace/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/notifications': RouteRecordInfo<
      '/notifications',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/owner/[name]': RouteRecordInfo<
      '/owner/[name]',
      '/owner/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/service/[name]': RouteRecordInfo<
      '/service/[name]',
      '/service/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/about'
      | '/settings/cloud'
      | '/settings/general'
      | '/settings/hosts'
      | '/settings/logs'
      | '/settings/security'
      | '/settings/sidebar'
      | '/settings/updates'
    >,
    '/settings/about': RouteRecordInfo<
      '/settings/about',
      '/settings/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/cloud': RouteRecordInfo<
      '/settings/cloud',
      '/settings/cloud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/general': RouteRecordInfo<
      '/settings/general',
      '/settings/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/hosts': RouteRecordInfo<
      '/settings/hosts',
      '/settings/hosts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/logs': RouteRecordInfo<
      '/settings/logs',
      '/settings/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/security': RouteRecordInfo<
      '/settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/sidebar': RouteRecordInfo<
      '/settings/sidebar',
      '/settings/sidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/updates': RouteRecordInfo<
      '/settings/updates',
      '/settings/updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/show': RouteRecordInfo<
      '/show',
      '/show',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stack/[name]': RouteRecordInfo<
      '/stack/[name]',
      '/stack/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'assets/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'assets/pages/cloud/search.vue': {
      routes:
        | '/cloud/search'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/container/[id].vue': {
      routes:
        | '/container/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'assets/pages/container/[id].time.[datetime].vue': {
      routes:
        | '/container/[id].time.[datetime]'
      views:
        | never
      pathParamNames:
        | 'datetime'
        | 'id'
    }
    'assets/pages/group/[name].vue': {
      routes:
        | '/group/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'assets/pages/host/[id].vue': {
      routes:
        | '/host/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'assets/pages/host-group/[name].vue': {
      routes:
        | '/host-group/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'assets/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/mcp/authorize.vue': {
      routes:
        | '/mcp/authorize'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/merged/[ids].vue': {
      routes:
        | '/merged/[ids]'
      views:
        | never
      pathParamNames:
        | 'ids'
    }
    'assets/pages/namespace/[name].vue': {
      routes:
        | '/namespace/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'assets/pages/notifications.vue': {
      routes:
        | '/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/owner/[name].vue': {
      routes:
        | '/owner/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'assets/pages/service/[name].vue': {
      routes:
        | '/service/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'assets/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/about'
        | '/settings/cloud'
        | '/settings/general'
        | '/settings/hosts'
        | '/settings/logs'
        | '/settings/security'
        | '/settings/sidebar'
        | '/settings/updates'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'assets/pages/settings/about.vue': {
      routes:
        | '/settings/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/cloud.vue': {
      routes:
        | '/settings/cloud'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/general.vue': {
      routes:
        | '/settings/general'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/hosts.vue': {
      routes:
        | '/settings/hosts'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/logs.vue': {
      routes:
        | '/settings/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/security.vue': {
      routes:
        | '/settings/security'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/sidebar.vue': {
      routes:
        | '/settings/sidebar'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/settings/updates.vue': {
      routes:
        | '/settings/updates'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/show.vue': {
      routes:
        | '/show'
      views:
        | never
      pathParamNames:
        | never
    }
    'assets/pages/stack/[name].vue': {
      routes:
        | '/stack/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
