/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuyMeCoffee: typeof import('./.vitepress/theme/components/BuyMeCoffee.vue')['default']
    Counter: typeof import('./.vitepress/theme/components/Counter.vue')['default']
    FinalCta: typeof import('./.vitepress/theme/components/FinalCta.vue')['default']
    HeroDemo: typeof import('./.vitepress/theme/components/HeroDemo.vue')['default']
    HeroTrust: typeof import('./.vitepress/theme/components/HeroTrust.vue')['default']
    InstallCommand: typeof import('./.vitepress/theme/components/InstallCommand.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsoredBy: typeof import('./.vitepress/theme/components/SponsoredBy.vue')['default']
    Stats: typeof import('./.vitepress/theme/components/Stats.vue')['default']
    Supported: typeof import('./.vitepress/theme/components/Supported.vue')['default']
    Testimonials: typeof import('./.vitepress/theme/components/Testimonials.vue')['default']
    WhyDozzle: typeof import('./.vitepress/theme/components/WhyDozzle.vue')['default']
  }
}
