/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserWindow: typeof import('./.vitepress/theme/components/BrowserWindow.vue')['default']
    BuyMeCoffee: typeof import('./.vitepress/theme/components/BuyMeCoffee.vue')['default']
    copy: typeof import('./.vitepress/theme/components/BrowserWindow copy.vue')['default']
    HeroVideo: typeof import('./.vitepress/theme/components/HeroVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
