version: "3.4"
services:
  custom_base:
    container_name: custom_base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=name=custom_base
      - DOZZLE_BASE=/foobarbase
    build:
      context: ..
  dozzle:
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=name=dozzle
    build:
      context: ..
  integration:
    build:
      context: .
    command: yarn test
    environment:
      - DEFAULT_URL=http://dozzle:8080/
      - CUSTOM_URL=http://custom_base:8080/foobarbase
    depends_on:
      - dozzle
      - custom_base
