version: "3.4"
services:
  custom_base:
    container_name: custom_base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=name=custom_base
      - DOZZLE_BASE=/foobarbase
      - DOZZLE_NO_ANALYTICS=1
    ports:
      - "8080:8080"
    build:
      context: ..
  dozzle:
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=name=dozzle
      - DOZZLE_NO_ANALYTICS=1
    ports:
      - "9090:8080"
    build:
      context: ..
  integration:
    build:
      context: .
    command: yarn test
    volumes:
      - ./__tests__:/app/__tests__
    environment:
      - DEFAULT_URL=http://dozzle:8080/
      - CUSTOM_URL=http://custom_base:8080/foobarbase
      - DOZZLE_NO_ANALYTICS=1
    depends_on:
      - dozzle
      - custom_base
