on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    uses: ./.github/workflows/_tests.yml
